--- #YAML:1.0
name:               Web-App
version:            1.14
abstract:           ~
author:
    - Ivan Baktsheev <dot.and.thing@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Easy:      0.06
    Data::Dump::XML:  1
    Project::Easy:    0.14
    XML::LibXSLT:     1.60
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Web-App
    homepage:    http://perlhug.com
    license:     http://dev.perl.org/licenses/
    repository:  git://web-app.git.sourceforge.net/gitroot/web-app/web-app
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
