--- #YAML:1.0
name:               Web-App
version:            1.1
abstract:           ~
author:
    - Ivan Baktsheev <dot.and.thing@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Easy:      0.02
    Data::Dump::XML:  1
    XML::LibXML:      1.6
    XML::LibXSLT:     1.6
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
